# Usar a imagem oficial do PostgreSQL
FROM postgres:latest

# Definir variáveis de ambiente para o banco de dados
ENV POSTGRES_DB=liberumdb
ENV POSTGRES_USER=liberum
ENV POSTGRES_PASSWORD=liberum

# Expor a porta padrão do PostgreSQL
EXPOSE 5432